### ISSUE TITLE
FAQ: Difference between method and function?

### ISSUE THREAD

**Issue by ghost** [code-mentoring/code-mentoring.github.io#30]

**Comment by mary-boti** [comment]
This is how a non-programmer sees the difference btw method and function: both show actions where function is customized and method is build-in (predefined) and always belongs to specific object

[Let's take one crazy example, making a tea lol where _tea=_**variable**, _tea.boilingWater_ is a **method** (is kinda predefined and must be taken + boiling the water is always the same) and _listeningMusic (type_of_music, when_to_listen)_ is a **function** - because it can customized, not must taken, and even can be used outside the event window]

*If something sounds weird to you hahahah pls blame lockdown lol

**Comment by mary-boti** [comment]
forgot to add, that making_afternoon_tea is a **class**

**Comment by edgul** [comment]
You're using a lot of words, like built-in and predefined, that carry too much meaning and this will easily cause unnecessary confusion. Also examples are nice, but we also need to be careful of using code, because sometimes code is just syntax and doesn't inform us on what is happening "under the hood".

Let me give a precise definition of each:
A function is a block of code we can easily reuse.
A method is a function that belongs to a class. Typically, it will operate on an instance's internal data.

**Comment by mary-boti** [comment]
Thanks a mil Ed. You are very good!

It's amazing to realize the power of diversity and inclusion. Hehehe we all are soooooo different and have a different perceptions and experiences :)

**Comment by ghost** [comment]
Added to our FAQ doc
